#SPDX-License-Identifier: MIT-0
---
# tasks file for role/nginx_dep_role

- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: yes

- name: Deploy nginx config template
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/000-default.conf
    mode: '0644'
    owner: root
    group: root
  notify: Restart nginx

- name: Enable nginx site configuration
  ansible.builtin.file:
    src: /etc/nginx/sites-available/000-default.conf
    dest: /etc/nginx/sites-enabled/000-default.conf
    state: link
  notify: Restart nginx

- name: Test Nginx Configuration
  ansible.builtin.command: nginx -t
  register: nginx_test
  failed_when: nginx_test.rc != 0
  changed_when: false

- name: Start and enable nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
